<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipo [
  <!ELEMENT equipo (jugador*)>
  <!ELEMENT jugador ((dorsal | puesto), nombre)>
  <!ELEMENT dorsal (#PCDATA)>
  <!ELEMENT puesto (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
]>
<equipo>
  <jugador>
    <dorsal>7</dorsal>
    <nombre>Cristiano Ronaldo</nombre>
  </jugador>
  
  <jugador>
    <puesto>Defensa Central</puesto>
    <nombre>Sergio Ramos</nombre>
  </jugador>
  
  <jugador>
    <dorsal>1</dorsal>
    <nombre>David de Gea</nombre>
  </jugador>
  
  <jugador>
    <puesto>Extremo Derecho</puesto>
    <nombre>Vin√≠cius Junior</nombre>
  </jugador>
</equipo>
