<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipo [
  <!ELEMENT equipo (jugador*)>
  <!ELEMENT jugador ((dorsal, puesto) | nombre)>
  <!ELEMENT dorsal (#PCDATA)>
  <!ELEMENT puesto (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
]>
<equipo>
  <jugador>
    <dorsal>7</dorsal>
    <puesto>Delantero</puesto>
  </jugador>
  
  <jugador>
    <nombre>Sergio Ramos</nombre>
  </jugador>
  
  <jugador>
    <dorsal>1</dorsal>
    <puesto>Portero</puesto>
  </jugador>
  
  <jugador>
    <nombre>Vin√≠cius Junior</nombre>
  </jugador>
  
  <jugador>
    <dorsal>15</dorsal>
    <puesto>Centrocampista</puesto>
  </jugador>
</equipo>
