=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="registroTemperatura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="provincia" type="xs:string" />
                <xs:element name="fecha" type="xs:date" />
                <xs:element name="temperaturaMinima">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="-50"></xs:minInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="temperaturaMaxima">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:maxInclusive value="55"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="incidencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="incidencia" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="frio"></xs:enumeration>
                                                    <xs:enumeration value="nieve"></xs:enumeration>
                                                    <xs:enumeration value="lluvia"></xs:enumeration>
                                                    <xs:enumeration value="calor"></xs:enumeration>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="severidad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="alta"></xs:enumeration>
                                                    <xs:enumeration value="media"></xs:enumeration>
                                                    <xs:enumeration value="baja"></xs:enumeration>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<registroTemperatura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio1.xsd">
    <provincia>Madrid</provincia>
    <fecha>2026-04-14</fecha>
    <temperaturaMinima>3</temperaturaMinima>
    <temperaturaMaxima>21</temperaturaMaxima>
    <incidencias>
        <incidencia>
            <nombre>lluvia</nombre>
            <severidad>media</severidad>
        </incidencia>
        <incidencia>
            <nombre>calor</nombre>
            <severidad>baja</severidad>
        </incidencia>
    </incidencias>
</registroTemperatura>
