=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogoMultimedia">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="obra" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="anio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="2000"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="libro" minOccurs="0">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="autor" type="xs:string" />
                                            <xs:element name="paginas">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:int">
                                                        <xs:minExclusive value="0"></xs:minExclusive>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="genero">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="drama"></xs:enumeration>
                                            <xs:enumeration value="comedia"></xs:enumeration>
                                            <xs:enumeration value="accion"></xs:enumeration>
                                            <xs:enumeration value="terror"></xs:enumeration>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                            </xs:choice>
                            <xs:element name="pelicula" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="director" type="xs:string" />
                                        <xs:element name="duracion">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minExclusive value="0"></xs:minExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogoMultimedia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio7.xsd">
    <obra id="O1">
        <titulo>El nombre del viento</titulo>
        <anio>2007</anio>
        <libro>
            <autor>Patrick Rothfuss</autor>
            <paginas>662</paginas>
        </libro>
        <genero>drama</genero>
    </obra>
    <obra id="O2">
        <titulo>Inception</titulo>
        <anio>2010</anio>
        <pelicula>
            <director>Christopher Nolan</director>
            <duracion>148</duracion>
        </pelicula>
        <genero>accion</genero>
    </obra>
</catalogoMultimedia>
