=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agendaContactos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contacto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{9}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^@]+/.[^@]+"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="empresa" minOccurs="0" type="xs:string" />
                                <xs:element name="amigo" minOccurs="0" type="xs:string" />
                            </xs:choice>
                            <xs:element name="direccion" minOccurs="0" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<agendaContactos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio8.xsd">
    <contacto id="C001">
        <nombre>Ana López</nombre>
        <telefono>612345678</telefono>
        <email>ana@example.com</email>
        <empresa>Tech Solutions</empresa>
    </contacto>
    <contacto id="C002">
        <nombre>Pedro García</nombre>
        <telefono>698765432</telefono>
        <email>pedro@gmail.com</email>
        <amigo>Universidad</amigo>
        <direccion>Calle Mayor 12</direccion>
    </contacto>
</agendaContactos>
