=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="autor" type="xs:string" />
                            <xs:element name="anyo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:maxInclusive value="1900"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:maxExclusive value="0"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required" />
                        <xs:attribute name="genero" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="novela"></xs:enumeration>
                                    <xs:enumeration value="ensayo"></xs:enumeration>
                                    <xs:enumeration value="poesia"></xs:enumeration>
                                    <xs:enumeration value="teatro"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio4.xsd">
    <libro isbn="9788401234567" genero="novela">
        <titulo>La sombra del viento</titulo>
        <autor>Carlos Ruiz Zafón</autor>
        <anyo>2001</anyo>
        <precio>19.95</precio>
    </libro>
    <libro isbn="9788467890123" genero="ensayo">
        <titulo>Historia breve</titulo>
        <autor>Maria Perez</autor>
        <anyo>2018</anyo>
        <precio>15.50</precio>
    </libro>
</biblioteca>
