=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente" type="xs:string" />
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="cantidad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minExclusive value="0"></xs:minExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="categoria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="informatica"></xs:enumeration>
                                                    <xs:enumeration value="hogar"></xs:enumeration>
                                                    <xs:enumeration value="moda"></xs:enumeration>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="promo" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio5.xsd">
    <pedido numero="1001">
        <cliente>Juan Torres</cliente>
        <producto promo="si">
            <nombre>Teclado mecánico</nombre>
            <cantidad>2</cantidad>
            <categoria>informatica</categoria>
        </producto>
        <producto>
            <nombre>Lámpara</nombre>
            <cantidad>1</cantidad>
            <categoria>hogar</categoria>
        </producto>
    </pedido>
</pedidos>
