=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="universidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="18"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="curso">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="primero"></xs:enumeration>
                                        <xs:enumeration value="segundo"></xs:enumeration>
                                        <xs:enumeration value="tercero"></xs:enumeration>
                                        <xs:enumeration value="cuarto"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:choice>
                                <xs:element name="beca" type="xs:string" />
                                <xs:element name="pago" type="xs:string" />
                            </xs:choice>
                            <xs:element name="observaciones" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="matricula" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Za-z0-9]+"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Tresillo2017/markup-language-1dam/U4/repaso-xsd/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio9.xsd">
    <alumno matricula="A12345">
        <nombre>Laura Martínez</nombre>
        <edad>21</edad>
        <curso>tercero</curso>
        <beca>Completa</beca>
        <observaciones>Intercambio Erasmus</observaciones>
    </alumno>
    <alumno matricula="B67890">
        <nombre>Carlos Ruiz</nombre>
        <edad>24</edad>
        <curso>cuarto</curso>
        <pago>Completo</pago>
    </alumno>
</universidad>
