<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel_vuelos [
  <!ELEMENT panel_vuelos (nombre_aeropuerto, vuelos, fecha)>
  <!ELEMENT nombre_aeropuerto (#PCDATA)>
  <!ELEMENT vuelos (vuelo+)>
  <!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
  <!ATTLIST vuelo
    codigo ID #REQUIRED
    estado (C|E|R) "E"
  >
  <!ELEMENT diario EMPTY>
  <!ELEMENT origen (#PCDATA)>
  <!ELEMENT destino (#PCDATA)>
  <!ELEMENT hora_salida (#PCDATA)>
  <!ELEMENT hora_llegada (#PCDATA)>
  <!ELEMENT fecha (#PCDATA)>
]>
<panel_vuelos>
  <nombre_aeropuerto>VM</nombre_aeropuerto>
  <vuelos>
    <vuelo codigo="V10" estado="R">
      <diario/>
      <origen>Alicante</origen>
      <destino>Madrid</destino>
      <hora_salida>9:30</hora_salida>
      <hora_llegada>10:30</hora_llegada>
    </vuelo>
    <vuelo codigo="V11" estado="C">
      <origen>Alicante</origen>
      <destino>Barcelona</destino>
      <hora_salida>10:15</hora_salida>
      <hora_llegada>12:15</hora_llegada>
    </vuelo>
  </vuelos>
  <fecha>28/11/2023</fecha>
</panel_vuelos>
